pageInfo:
  - pageName: 'Home'
    pageLink: '/'
    displayInNav: true
  - pageName: 'About'
    pageLink: '/About'
    displayInNav: true
  - pageName: 'Blog'
    pageLink: '/Blog'
    displayInNav: true
  - pageName: 'Events'
    pageLink: '/Events'
    displayInNav: true
  - pageName: 'Contact Us'
    pageLink: '/Contact'
    displayInNav: true
bannerInfo:
  text: 'HACKATHON 2024, coming to Trent, [Learn More](example.com)!'
# please refer to https://react-icons.github.io/react-icons/icons/ for possible icons
heroIcons:
  - altText: Link to TCSCA Instagram
    link: https://www.instagram.com/trentcsca/
    path: /Icons/instagram.svg
  - altText: Link to TCSCA Linkedin
    link: https://www.linkedin.com/company/trent-computer-science-society
    path: /Icons/linkedin.svg
  - altText: Link to TCSCA Discord
    link: https://discord.gg/serea2sPAd
    path: /Icons/discord.svg
aboutUs:
  text: The Trent Computer Science Club Association (TCSCA) is a club that aims to provide a supportive community for computer science students at Trent University. Our mission is to create a welcoming and inclusive environment where students can learn, grow, and have fun while developing their skills and interests. We love Open Source and are always looking for new ways to contribute to the community. CHANGE ME!!!
  image: /AboutUsPlaceHolder.jpg
  altText: About Us Image
